// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { browserEnv } from '@/lib/env';
const { supabaseUrl, supabasePublishableKey } = browserEnv;

// ✅ Validate required environment variables
if (!supabaseUrl || !supabasePublishableKey) {
  throw new Error(
    `Missing required Supabase environment variables:\n` +
    `SUPABASE_URL: ${supabaseUrl ? "correct" : "wrong"}\n` +
    `SUPABASE_PUBLISHABLE_KEY: ${supabasePublishableKey ? "correct" : "wrong"}`
  );
}

export const supabase = createClient(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistence: 'session',
    autoRefreshToken: true,
  },
});
  
;